### ISSUE TITLE
More Materials

### ISSUE THREAD

**Issue by Furballllllll** [Kikugie/elytra-trims#10]
There's a datapack that adds new armor trim materials such as echo shards, glowstone and coal and I really like the glowstone trim so I would really appreciate it if you considered adding this

Link: https://www.planetminecraft.com/data-pack/more-armor-trim-materials/

**Comment by kikugie** [comment]
Should be fixed in 1.1.10-beta along with any other trim material datapack. If you have issues with the new feature, please create a new issue report for it.
