### ISSUE TITLE
Elytra does not Render Trim, Dyes or Banners

### ISSUE THREAD

**Issue by azervera** [Kikugie/elytra-trims#11]
## Description

-Multiplayer Server- Elytra trims can be added and register under the "item description" but fails to render the trim. Dyes and banners also do not work. Double checked the versions, server type, etc. Apologies in advance as i am still newer to modded minecraft. 

## To Reproduce

1. Open Minecraft
2. log into server
3. trim elytra
4. trim and material is applied, no change from default appearance

What you expect to see: Trimmed Elytra

What actually happens: Trim and Material is applied but fails to render image

## Environment

Describe the environment to reproduce this bug:

- Minecraft version: 1.20.1
- TemplateMod version: Fabric
- Other related mod versions: N/A

**Comment by kikugie** [comment]
Make sure the default resourcepack is enabled in the vanilla menu. Minecraft might've disabled it if at some point there was a resource loading error. Since mod version 1.1.6 it can be force-enabled in the mod config.

**Comment by solonovamax** [comment]
Also, it sounds like they added it server side and not client side, as they specifically specified it only happening on a server.

**Comment by kikugie** [comment]
This is probably caused by a resource reload failing on older versions of the mod, but I can't investigate without logs.
