### ISSUE TITLE
error during launch with CIT & ETF

### ISSUE THREAD

**Issue by DadoIrie** [Kikugie/elytra-trims#12]
Having Elytra Trims with [CIT Resewn](https://modrinth.com/mod/cit-resewn) & [ETF](https://modrinth.com/mod/entitytexturefeatures) console throws a huge error during launch 
disabling either one of those 3 mods does not trigger the error

ET + CIT + ETF = error

ET + CIT = no error
ET + ETF = no error
CIT + ETF = no error

hope this helps

## Log

https://mclo.gs/6KhvRPv
https://mclo.gs/jxXHG24 (with command-config)

EDIT: forgot to mention that I did try it also with Elytra Trims 1.1.9 as I've thought it might have been that 1.1.10 addition/change, but error still appeared also with 1.1.9

**Comment by kikugie** [comment]
Fixed in 1.1.10-beta.2 👍  
Download it from Modrinth or Github, as Curseforge takes some time to approve files.
