### ISSUE TITLE
Modded Banner support

### ISSUE THREAD

**Issue by Zartrix** [Kikugie/elytra-trims#15]
I'm playing with a small private mod pack, in which Elytra Trims as well as [Additional Banners](https://modrinth.com/mod/additional-banners) and [Archaeology Banners](https://modrinth.com/mod/archaeology-banners) are included.

I decided to test around if Elytra Trims and both banner mods would work out of the box, but it didn't.
Not only that, but I tried to add the "elytra_patterns" sources in the "armor_trims" atlas, but I assume that just does not work this way?

So, is there any way to add modded banners using a resource pack, or does it need to be coded in? And if it's the latter, would it be possible to do that?

**Comment by kikugie** [comment]
It should be possible, but for some reason it breaks on rendering. It will be fixed in the main mod, and compatibility resourcepacks will be added to the extensions

**Comment by kikugie** [comment]
Will be in the next update 👍
