### ISSUE TITLE
A way to make Resource Packs not affect modded Elytras?

### ISSUE THREAD

**Issue by Diego13303** [Kikugie/elytra-trims#16]
This is not an issue, maybe it counts as a request. I just didn´t know where else to ask about it
I wanted to use a resource pack that changes how Elytra look, but the trims look kinda bad on them. Is there any way I can make it so trimmed Elytras aren´t affected by the Resource Pack? I assumed they´d use a separate texture but that doesn´t seem to be the case

**Comment by kikugie** [comment]
Trims work as in vanilla, by overlaying on top of the existing texture. Minecraft can't really identify if your texture is the original, so a way to solve this would be either to create a resourcepack with trims for that model or disable trim rendering in the mod config.
