### ISSUE TITLE
[BUG] stacked trims compatibility broken (& technically outdated)

### ISSUE THREAD

**Issue by notandvm** [Kikugie/elytra-trims#17]
## Description

when using the stacked armor trims mod, only the first applied trim properly renders
inventory tooltip displays all applied trims correctly

![2023-07-28_19 11 59](https://github.com/kikugie/elytra-trims/assets/137728158/cacd06ab-7a51-4099-bc0d-0392c6ade5e1)
![2023-07-28_19 30 17](https://github.com/kikugie/elytra-trims/assets/137728158/00a084ff-b888-41d0-ad70-5c4cd8908fd4)

## Environment

base 1.20.1 fabric instance

fabric api (_0.86.1_)
stacked armor trims (_1.1.0_)
elytra trims (_1.1.10-beta.3_)

* note: mod being used is [Stacked Armor Trims](https://modrinth.com/mod/stacked-armor-trims), _not_ [Stackable Trims](https://modrinth.com/mod/stackable-trims) as listed in etrim's changelogs. this is due to the downloads for the latter having been removed by the creator, likely due to S.A.T. being updated; which may be the cause for the issue

**Comment by kikugie** [comment]
👍
