### ISSUE TITLE
All letter are square when launching the game.

### ISSUE THREAD

**Issue by TimelessKeeper** [Kikugie/elytra-trims#18]
### Bug description

All letter are square when launching the game.

![Capture d’écran 2023-07-31 114836](https://github.com/kikugie/elytra-trims/assets/96741573/343d73ac-c234-4671-b6c3-dd4984301608)

Mod used when the bug appear:
Elytra Trim 1.1.10-beta4
MoreArmorTrims 1.0.1
All the trim 3.1.2

The bug doesn't appear if one of this three mod is not present

### Steps to reproduce

1. Add all tree mod
2. Open the game

### Relevant logs

https://mclo.gs/C0vfFNT

### Minecraft version

1.20.1

### Elytra Trims version

1.1.10-beta.4

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by kikugie** [comment]
Should be fixed in the next All The Trims update

**Comment by TimelessKeeper** [comment]
Yes, it's working now
