### ISSUE TITLE
Set client side requirement to "Optional" on modrinth

### ISSUE THREAD

**Issue by solonovamax** [Kikugie/elytra-trims#19]
### Bug description

Currently, it is marked as being "Required" client-side on modrinth. This implies that if a server has it and a client doesn't they cannot connect, but if a server doesn't have it and a client does then they can connect.
According to the description, this is false, as it can run optionally on both sever side and client side.

### Steps to reproduce

1. Open modrinth

### Expected behavior

Marked as "Optional" for the client.

### Actual behavior

Marked as "Required" for the client.

### Relevant logs

N/A

### Minecraft version

N/A

### Elytra Trims version

N/A

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by kikugie** [comment]
Good point, fixed. 👍
