### ISSUE TITLE
[Fabric] Trims not rendered in back slot with Elytra Slot

### ISSUE THREAD

**Issue by teleheel** [Kikugie/elytra-trims#20]
### Expected behavior

Trims rendering when equipping the elytra in the back/cape slot.

### Actual behavior

No trims are rendered.

### Mod links

https://modrinth.com/mod/elytra-slot

### Other information

Tested with the latest version of the Fabric Loader, Fabric API, Elytra Slot and Elytra Trims.

Seems like the problem in #5 is back :/

**Comment by kikugie** [comment]
Fixed in 1.2.1
