### ISSUE TITLE
Elytra Trims Breaks Main Menu in Prominence II Modpack 

### ISSUE THREAD

**Issue by Avakining** [Kikugie/elytra-trims#21]
### Expected behavior

The main menu of the modpack renders correctly (as shown in screenshot): 
<img width="1512" alt="Screenshot 2023-08-08 at 11 21 54" src="https://github.com/kikugie/elytra-trims/assets/25210618/df013f90-6c70-4437-9bee-c54a19f479f8">

### Actual behavior

The main menu of the modpack renders with buttons all over the place:
<img width="1512" alt="Screenshot 2023-08-08 at 11 23 31" src="https://github.com/kikugie/elytra-trims/assets/25210618/3c027ae6-8fc6-48a3-894e-ed91fa363c2a">

### Mod links

https://legacy.curseforge.com/minecraft/modpacks/prominence-2-fabric (v 0.7.0 for 1.20.1)

### Other information

The only difference is the addition of Elytra Trims. Not sure why/how the main menu would be affected still. This is

**Comment by kikugie** [comment]
This modpack has an outdated version of All The Trims, which has compatibility issue. Update it in the modpack installation: https://modrinth.com/mod/allthetrims/version/3.1.4
