### ISSUE TITLE
Config is null - 1.3.0 1.20.1 Fabric

### ISSUE THREAD

**Issue by xR4YM0ND** [Kikugie/elytra-trims#25]
### Bug description

Config is null / empty

### Steps to reproduce

Just the usual

### Relevant logs

https://gist.github.com/xR4YM0ND/66b40eb9e684ebd4586f3c8c7f284930#file-crash-report-L248

### Minecraft version

1.20.1

### Elytra Trims version

1.3.0

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by kikugie** [comment]
Same issue as #23

**Comment by xR4YM0ND** [comment]
It also crashes the game, just disabled the mod and now i can create and join a world.

With this mod i couldnt

( Crash Report linked as gist )

**Comment by kikugie** [comment]
I know, I'm not able to fix it until the end of the weekend, so use 1.2.1

**Comment by xR4YM0ND** [comment]
Alrighty, thx for maintaining and the fast reply !
