### ISSUE TITLE
Trims not showing while using Resource Packs

### ISSUE THREAD

**Issue by Lycrom** [Kikugie/elytra-trims#27]
### Bug description

With Version 1.3.3 for 1.20 I do not see the Trims / Dyes etc applied to my Elytra while I have a resource Pack Selected. It doesn't matter if the Resource Pack affects Elytras or not, as soon as one is applied it stops showing them. 

If I go back to Version 1.2.1 of Elytra Trims then it works just fine, which is why I think this may be a bug.

I have a long list of mods so I don't know if this is another mod causing this. 

### Steps to reproduce

1. Have an Elytra with Trims etc.
2. Select a Resource Pack
3. Don't see Trim anymore

### Expected behavior

I expect to see the Trims as I did in the older Version

### Minecraft version

1.20.1

### Elytra Trims version

1.3.3

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by kikugie** [comment]
Please send the full game log via https://mclo.gs

**Comment by Lycrom** [comment]
https://mclo.gs/cur5h1y
I have also tried adding the latest version of Command Config lib, but that hasn't changed anything.

**Comment by kikugie** [comment]
Rather confusing. I'm testing it with mods from your log and faithful 32x, and can't reproduce it.  
Can you test if this problem occurs with no mods other than ET? Also when it occurs, press F3+S in game and open the prompted `debug` folder. In there check if `elytratrims_elytra_features_0.png` looks somewhat like this:  
![elytratrims_elytra_features_0](https://github.com/kikugie/elytra-trims/assets/50152507/da7c2cb8-0758-4407-9783-fca4524f39ae)

**Comment by Devoev** [comment]
I'm having a similar issue. Manually reloading the resource packs when in game temporarily fixes the issue. But I think the bug orignates from DashLoader (the 1.20 version is still in beta...). At least in my case, removing DashLoader fixed the issue

**Comment by kikugie** [comment]
Thanks for the info. I'll try it when I'll be available.

**Comment by kikugie** [comment]
Making a proper compatibility will take some time, but in the meantime you can press F3+T in game to fix it. (Quite tedious to do every time, yea)
