### ISSUE TITLE
Dyes don't show up on elytra

### ISSUE THREAD

**Issue by Tri-Iris** [Kikugie/elytra-trims#28]
### Bug description

Elytra dyeing doesn't work, It says it is dyed, but no color shows up when worn

### Steps to reproduce

1. Start the game as usual with mod
2. Make a dyed elytra with colors
3. Nothing happens.

### Expected behavior

Supposed to dye elytra. 

### Actual behavior

When worn, color doesn't show up.

### Minecraft version

1.20.1

### Elytra Trims version

1.3.3

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by kikugie** [comment]
Fixed build will be at https://github.com/kikugie/elytra-trims/actions/runs/6133643437 (when its done, click on "download artifacts" at the bottom, and use non-sources file from those)
