### ISSUE TITLE
Mod becoming non-functional after closing/reopening a singleplayer world

### ISSUE THREAD

**Issue by solxradiation** [Kikugie/elytra-trims#3]
Mod operates perfectly fine upon first installation, but closing and reopening the singleplayer world makes all the color, trims, etc disappear from the elytra. In the inventory, elytras still show the trim and color in the description. If you uninstall the mod, open the world, close the world, and then reinstall the mod, everything works as intended. 

## To Reproduce

1. Install mod
2. Open singleplayer world 
3. Use dye and/or trim on an elytra
4. Close game
5. Reopen game
6. View elytra outside the inventory, visual changes are gone

## Environment 

Minecraft version 1.20.1
Fabric version 0.14.21-1.20.1
Mod version 1.1.5 for 1.20

**Comment by kikugie** [comment]
This mod has a default resourcepack for client-side visuals. It can be disabled by the game itself if resource reload fails. Check it in `Options -> Resource packs`.  
Resource reload fail can be caused by a mod conflict. Do you mind uploading client log to https://mclo.gs/, so I can look for it?

**Comment by solxradiation** [comment]
Ah, yeah it seems like the resource pack was disabling itself somehow. It seems to be doing okay now (maybe since I manually loaded the pack?), but I've uploaded the logs from when I noticed the issue. Thanks for the help!
https://mclo.gs/KREs6DH
https://mclo.gs/G7s9irT
https://mclo.gs/5Wfgi8Q
https://mclo.gs/w3EHz77

**Comment by kikugie** [comment]
1.1.6 adds a workaround if this keeps happening
