### ISSUE TITLE
[Resourcepack Crash] sprite is null - ETAtlasHolder - Fabric 1.20.1 v1.3.3

### ISSUE THREAD

**Issue by xR4YM0ND** [Kikugie/elytra-trims#30]
### Bug description

The 1.3.3 version crashes all resourcepacks (even vanilla)

### Steps to reproduce

Install Elytra Trims 1.3.3

### Relevant logs

Line 1248

https://gist.github.com/xR4YM0ND/1cbab3026f0e84281a25faab04e81de1

### Minecraft version

1.20.1

### Elytra Trims version

1.3.3

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by kikugie** [comment]
Do you have reaourcepacks or mods affecting shield textures there?

**Comment by xR4YM0ND** [comment]
## Mods
- "Guarding" adds their own Shield
- "EarlyStage" adds their own Shield (disabled in newest version)

I try it without them, gimme 2 min

**Comment by kikugie** [comment]
The mod fails to load a banner pattern texture, but fails for aome reason. It really should just skip that case instead of crashing, but it would be helpful to narrow down the problem.

**Comment by xR4YM0ND** [comment]
"Sleep Tight" should be the mod causing this (adds Banner Pattern)
https://modrinth.com/mod/sleep-tight

**Comment by kikugie** [comment]
Alright, thanks. I'll fix when at PC 👍

**Comment by xR4YM0ND** [comment]
Thank you as well <3

**Comment by kikugie** [comment]
L Github
