### ISSUE TITLE
Mythic Metals compat

### ISSUE THREAD

**Issue by InspectorBoat** [Kikugie/elytra-trims#31]
### Motivation

Mod compat!

### Description

Mythic Metals adds a celestium elytra item, which don't accept trims with this mod installed. When upgrading from a normal elytra to a celestium elytra, the existing trim is removed, and new trims cannot be added.

### Other information

[](https://github.com/Noaaan/MythicMetals/blob/1.20/src/main/java/nourl/mythicmetals/armor/CelestiumElytra.java)

**Comment by kikugie** [comment]
Implemented in 2.0
