### ISSUE TITLE
trims not working, crash when reloading textures

### ISSUE THREAD

**Issue by DXLUSION** [Kikugie/elytra-trims#33]
### Bug description

Elytra trims do not show up in game, triggering a texture reload with F3+T crashes the game.

### Steps to reproduce

- Start the game and join a single/multi player world
- equip an elytra with an armor trim applied
- Press F3+T

### Expected behavior

Elytra trim shows up, game doesn't crash when pressing F3+T

### Actual behavior

No armor trim appears on the elytra and the game crashes when pressing F3+T

### Relevant logs

https://mclo.gs/UzHmS4Z

### Minecraft version

1.20.2

### Elytra Trims version

1.4.3

### Other information

I've removed all my mods and resourcepacks and yet the error is still present.
Same behavior is also present on a multiplayer server.
I've also tried using a different version of Fabric API but no luck.

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by kikugie** [comment]
Fastest past midnight fix in ye olde west
