### ISSUE TITLE
Crashes for no reason?

### ISSUE THREAD

**Issue by Tri-Iris** [Kikugie/elytra-trims#35]
### Bug description

It's a crash that happens with just the mod. 

### Steps to reproduce

1. Add Elytra Trims
2. Crashes
3. That's literally it

### Expected behavior

Start the actual game

### Actual behavior

Decides to blow up and crash ig

### Relevant logs

https://mclo.gs/u1CrBp4

### Minecraft version

1.20.2

### Elytra Trims version

2.0.0-beta.2 and 2.0.0-beta

### Other information

Something may have happened when fixing the compatibility with YUNG's mod, because it seemed like their thing was fixed. I did tests to see if it was other mods, but when I putted it by itself with just the fabric api, it just doesn't work. Edit: It was also done in the Mondrinth Launcher. Felt like that was important.

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by kikugie** [comment]
2.0.0-beta.3 for 1.20.2/.4 has been uploaded to modrinth and curseforge
