### ISSUE TITLE
[Bug]: Elytra Trims provides a broken implementation of ModMenuApi

### ISSUE THREAD

**Issue by anticode-403** [Kikugie/elytra-trims#37]
### Mod loader

Fabric

### Minecraft version

1.20.1

### Mod version

2.0.0-beta.4

### Affected mods

- [X] Elytra Trims
- [ ] Extensions

### Bug description

As far as I can tell, this doesn't actually cause any issues, but it _would_ be nice to remove some of the red text in my logs.

### Relevant logs

https://mclo.gs/KvOVN8e

**Comment by kikugie** [comment]
The installed version in the log is `2.0.0-beta.2`, the bug is fixed in `2.0.0-beta.4`
