### ISSUE TITLE
[Bug]:  Trims are not displaying on server

### ISSUE THREAD

**Issue by aazza94** [Kikugie/elytra-trims#39]
### Mod loader

Fabric

### Minecraft version

1.20.4

### Mod version

2.0.0 beta 4, 1.4.5

### Affected mods

- [X] Elytra Trims
- [X] Extensions

### Bug description

I have installed the mod on my fabric server, I am able to dye the elytra's, trim them etc everything works great. However, the elytra's do not display as dyed or trimmed. This is the same for everybody on the server. Here is my servers list of mods in case you know of any conflictions but there doesn't seem to be.

AxesAreWeapons-1.7.3-fabric-1.20.2.jar	26.89kB	27/01/2024 20:26:16	
balm-fabric-1.20.4-9.0.5.jar	386.65kB	27/01/2024 20:44:43	
bigger_end_cities-1.20.4-1.0.4.jar	28.98kB	27/01/2024 20:33:16	
bundle-recipe-v1.0.0.jar	3.29kB	27/01/2024 20:32:58	
cloth-config-13.0.121-fabric.jar	1.09MB	27/01/2024 20:26:13	
collective-1.20.4-7.30.jar	703.48kB	27/01/2024 20:44:40	
command-config-0.1.0-beta.4+1.20.jar	56.38kB	30/01/2024 13:25:58	
cristellib-1.2.2-fabric.jar	418.63kB	27/01/2024 20:22:25	
cryingportals-1.20.4-2.7.jar	34.41kB	27/01/2024 20:29:10	
doubledoors-1.20.4-5.2.jar	51.08kB	27/01/2024 20:20:57	
elytratrims-fabric-2.0.0-beta.4+1.20.4.jar	173.75kB	30/01/2024 13:36:40	
elytratrims_extensions-fabric-2.0.0.jar	41.01kB	30/01/2024 13:27:11	
fabric-api-0.95.1+1.20.4.jar	2.04MB	27/01/2024 20:18:11	
ferritecore-6.0.3-fabric.jar	122.17kB	27/01/2024 20:47:08	
floodgate-fabric-2.2.0-SNAPSHOT+build.17.jar	5.52MB	28/01/2024 17:57:29	
Geyser-Fabric.jar	12.99MB	28/01/2024 17:40:16	
inventorytotem-1.20.4-3.2.jar	23.34kB	27/01/2024 20:26:44	
krypton-0.2.6.jar	163.25kB	27/01/2024 20:48:15	
letmedespawn-fabric-1.20.x-1.2.0.jar	77.11kB	27/01/2024 20:49:25	
lithium-fabric-mc1.20.4-0.12.1.jar	699.24kB	27/01/2024 20:47:06	
memoryleakfix-fabric-1.17+-1.1.5.jar	48.18kB	27/01/2024 20:47:11	
midnightlib-fabric-1.5.3.jar	50.06kB	27/01/2024 20:44:46	
more_mobs-v1.5.1-mc1.14x-1.20x-mod.jar	148.57kB	27/01/2024 20:27:20	
morezombievillagers-1.20.4-3.5.jar	23.54kB	27/01/2024 20:30:05	
passiveendermen-1.20.4-4.6.jar	35.39kB	27/01/2024 20:45:49	
RecipeCooldown-1.0.0.jar	19.96kB	29/01/2024 05:35:04	
repurposed_structures-7.2.4+1.20.4-fabric.jar	7.62MB	27/01/2024 20:22:52	
restart-server-1.2.0+mc1.19.x-1.20.x.jar	44.31kB	30/01/2024 12:16:53	
spawnanimations-v1.9.4-mc1.17x-1.20x-mod.jar	74.61kB	27/01/2024 20:24:03	
threadtweak-fabric-1.20.4-0.1.2.jar	140.85kB	27/01/2024 20:50:11	
tool-trims-mod-v2-0-2e-1-20.jar	1.53MB	27/01/2024 20:28:29	
Towns-and-Towers-1.12.0.jar	2.68MB	27/01/2024 20:22:23	
vmp-fabric-mc1.20.4-0.2.0+beta.7.136-all.jar	445.85kB	29/01/2024 05:33:26	
yet-another-config-lib-fabric-3.3.2+1.20.4.jar	956.32kB	30/01/2024 13:26:21	

One thing I have noticed is that "command config lib" which is a prerequisite for this mod, hasn't updated to 1.20.4 yet. Could this possibly be the reason for it? I doubt it but I thought I would mention it.

Thank you!

### Steps to reproduce

1. Install Elytra Trims to the fabric mod folder (server only Pebblehost)
2. Install Elytra Extensions (server only)
3. Reboot server
4. Log into the server
5. Dye Elytra (trimming is same)
6. Wear Elytra
7. No colour or trim displaying, just the default elytra model.

**Comment by kikugie** [comment]
Elytra Trims needs to be installed on clients to be able to see the trims.  
Also, Extensions are only client-side and won't do anything if you don't have mods that add the compatible trims (i.e. More Armor Trims, Geode+, Frostiful)
