### ISSUE TITLE
[Feature request] Glass armor compatability

### ISSUE THREAD

**Issue by steve-the-player** [Kikugie/elytra-trims#40]
### Description

[Glass Armor](https://modrinth.com/mod/glass-armor/) introduces a glass ingot, which when used to craft armor makes it invisible. Even without the cosmetic armor mod, this can be useful for just seeing what trims will look like, because the trims still render. It would be cool to be able to craft a trimmed elytra with a glass ingot (if Glass Armor is installed ofc) to make the actual wing portion of the elytra invisible, only rendering the elytra trims.

**Comment by kikugie** [comment]
Glass Armor adds new items, which Elytra Trims avoids by design. You can achieve the same effect client-side with [SMYS](https://modrinth.com/mod/show-me-your-skin)

**Comment by steve-the-player** [comment]
Really, the trims still show up when the elytra's hidden? I'll have to check that out then
