### ISSUE TITLE
[Feature Request]: Displaying elytra colour on the item

### ISSUE THREAD

**Issue by anoomolu** [Kikugie/elytra-trims#41]
### Mod loader

Fabric

### Minecraft version

1.20.1

### Mod version

2.0.0-beta.4

### Affected mods

- [X] Elytra Trims
- [ ] Extensions

### Bug description

Hiya, first off thank you for making this mod. I'm really enjoying messing around with the various dye and trim options to pair with my armour.

One thing I noticed is that while leather armour displays the dyed output when applying dyes, elytra doesn't do the same, and doesn't show the colour on the elytra. Would it be possible to make it work the same as leather armour/horse armour? Below has them both side-by-side with the same dye applied.

![image](https://github.com/kikugie/elytra-trims/assets/77850233/9b7f7637-d8aa-43bc-be84-40e9386ce4b5)

**Comment by kikugie** [comment]
It is planned along with glow and banner previews. I'll mark it as a feature request for now.

**Comment by kikugie** [comment]
Done in 3.0
