### ISSUE TITLE
[Bug]: Elytra still getting Cape texture

### ISSUE THREAD

**Issue by peow** [Kikugie/elytra-trims#45]
### Mod loader

Fabric

### Minecraft version

1.20.1

### Mod version

2.0.0-beta.4

### Affected mods

- [X] Elytra Trims
- [ ] Extensions

### Bug description

when configuring the mod so that the texture of the Capes is not showed on Elytra, it only has an effect on the Chestplate Slot, on the Trinket Slot it still has the texture of the cape

![2024-02-26_22 17 42](https://github.com/kikugie/elytra-trims/assets/105888751/5481539a-e292-4a4a-a1b8-b6cb9102f44f)
![2024-02-26_22 17 27](https://github.com/kikugie/elytra-trims/assets/105888751/de87fb20-76fc-4b6d-986a-cc3ef76ac1fb)
![2024-02-26_22 17 33](https://github.com/kikugie/elytra-trims/assets/105888751/117a2d34-a768-4b33-b609-eb2644e6125e)
![2024-02-26_22 17 38](https://github.com/kikugie/elytra-trims/assets/105888751/102fa3b9-e94a-4bde-83be-c131367691c3)

**Cape Slot**
![2024-02-26_22 17 46](https://github.com/kikugie/elytra-trims/assets/105888751/7e9a7d5e-da6f-4068-bed2-167fcf20bf11)
![2024-02-26_22 17 48](https://github.com/kikugie/elytra-trims/assets/105888751/d4244dd6-0dd2-4cc5-999a-9ee34378c670)

----------------

I tested both with the **Elytra Slot** mod and the **Clutter** mod which also allows you to use Elytras in the Cape Slot

if possible pls make an update to fabric 1.20.1 with support to fabric loader 0.14.22, thanks

### Steps to reproduce

Use Elytra Trims, Trinkets and Elytra Slot or Clutter

**Comment by kikugie** [comment]
Issues with Elytra Slot have been fixed in the latest commit. Clutter 0.6 is currently in development, a fix for it will be added when the update is finished.

Also won't make floader 0.14 support - just install 0.15.

**Comment by peow** [comment]
If I change to version 0.15.7 of the fabric loader in a modpack made for 0.14.22, will this cause instabilities? crashes etc?

**Comment by kikugie** [comment]
Extremely unlikely

**Comment by kikugie** [comment]
Working in current mod versions, reopen when Clutter updates if needed
