### ISSUE TITLE
[Bug]: Version 2.0.2 throws an error if any Elytra-related mods are installed alongside it

### ISSUE THREAD

**Issue by DarthCaesium** [Kikugie/elytra-trims#46]
### Mod loader

Forge

### Minecraft version

1.20.1

### Mod version

2.0.2

### Affected mods

- [X] Elytra Trims
- [ ] Extensions

### Bug description

When the latest version is installed, if any Elytra-related mods are installed alongside it, there will be an error message thrown by those other Elytra-related mods and will the game will refuse to properly start.

### Steps to reproduce

1) Install version 2.0.2 of Elytra Trims on Forge 1.20.1.
2) Install any mod that messes with Elytras, e.g. Elytra Physics, Elytra Slot, etc.
3) Launch the game.

### Relevant logs

https://mclo.gs/YzKOLD6

**Comment by kikugie** [comment]
Fixed in 2.0.3 👍
