### ISSUE TITLE
[Bug]: Crash with latest update

### ISSUE THREAD

**Issue by ghost** [Kikugie/elytra-trims#47]
### Mod loader

Forge

### Minecraft version

1.20.1

### Mod version

elytratrims-forge-2.0.2+1.20.1

### Affected mods

- [X] Elytra Trims
- [ ] Extensions

### Bug description

Crash at launch

### Steps to reproduce

Launch game

### Relevant logs

https://paste.dedimc.io/isacigequz.properties

**Comment by kikugie** [comment]
There's no mention of elytra trims in the logs (except for the mod list ofc). The log suggests this to be the problem:
![image](https://github.com/kikugie/elytra-trims/assets/50152507/6ed58717-4c84-4d24-94f0-39e849db0703)

If that doesn't help, please test the issue with fewer mods.

**Comment by ghost** [comment]
The crash disappears when i remove Elytra Trims, and comes back when i add it. I'm sure it is Elytra Trims relevant.

I tested carefully.

**Comment by kikugie** [comment]
I can't know what the issue is among 529 mods, especially without having them installed myself and with no mention of Elytra Trims in the log.
If you have it, please send the full game log. Hopefully it will provide enough information, but otherwise I won't be able to fix it until you have a more narrowed down problem.

**Comment by ghost** [comment]
[latest.log](https://github.com/kikugie/elytra-trims/files/14426150/latest.log)

I've uploaded the log hopefully it may help?

**Comment by kikugie** [comment]
It has the same error as in #46. Try updating it to 2.0.3.

**Comment by ghost** [comment]
I'll update you tomorrow when i get the chance to test 2.0.3.
You could close the issue and I will reopen it if the crash presists with 2.0.3.

Thank you for your quick responses!

**Comment by ghost** [comment]
I managed to test it, crash is gone with 2.0.3, Thank you kindly!
