### ISSUE TITLE
[Bug]: does not work on Optifine

### ISSUE THREAD

**Issue by RadikCells** [Kikugie/elytra-trims#49]
### Mod loader

Forge

### Minecraft version

1.20.1

### Mod version

2.0.0-2.0.3

### Affected mods

- [X] Elytra Trims
- [ ] Extensions

### Bug description

when you try to start the game, it crashes. If you run it without it, the mod works

### Steps to reproduce

1. Install OptiFine
2. Launch the game
3. Crash
[crash-2024-03-15_22.05.54-client.txt](https://github.com/kikugie/elytra-trims/files/14619715/crash-2024-03-15_22.05.54-client.txt)

**Comment by kikugie** [comment]
It is known to be incompatible with optifine and it won't be fixed. On forge use [Embeddium](https://modrinth.com/mod/embeddium) and [Oculus](https://modrinth.com/mod/oculus) for fps boosts and shader support.

**Comment by RadikCells** [comment]
then please change the information on the website that the mod does not work with OptiFine, not OptiFabric
