### ISSUE TITLE
Incompatibility with Elytra Slot

### ISSUE THREAD

**Issue by DJChaos42** [Kikugie/elytra-trims#5]
## Description

When using the Elytra Slot mod, trims do not render if an Elytra is placed in the back slot.

## To Reproduce

1. Create a trimmed Elytra
2. Place the Elytra in the back slot
3. Observe that the trim patterns do not render on the Elytra

What you expect to see: Elytras placed in the back slot will render their trim patterns the way they do when placed in the chestplate slot

What actually happens: No trim patterns are rendered

## Environment

Describe the environment to reproduce this bug:

- Minecraft version: 1.20.1
- Elytra Trims version: 1.1.7
- Elytra Slot version: 6.3.0
- Trinkets version: 3.7.0

**Comment by kikugie** [comment]
I've added a compatibility fix, try using version from this build artifact: https://github.com/kikugie/elytra-trims/actions/runs/5339549847  
Lmk if there are any issues with it, otherwise I'll upload a release in a couple of days

**Comment by kikugie** [comment]
Fixed in 1.1.8
