### ISSUE TITLE
[Bug]: Mod Compat Breaking

### ISSUE THREAD

**Issue by mxnmnm** [Kikugie/elytra-trims#51]
### Mod loader

NeoForge

### Minecraft version

1.20.1

### Mod version

Elytra trims: 2.0.5
Elytra trims extensions: 2.0

### Affected mods

- [X] Elytra Trims
- [X] Extensions

### Bug description

Elytra trims and extensions is lacking mod compat

Elytras from mekanism, alex's mobs, and better end (using sinytra connector) don't work with any trims

The armor trim from more sniffer flowers doesn't show

### Steps to reproduce

Try to put a trim on any of the elytras listed above or use the armor trim from more sniffer flowers on a normal elytra and see both issues happen :(

**Comment by kikugie** [comment]
Mekanism and BetterEnd compatibility has been fixed in 2.1.1.  
Alex's Mobs won't be because it uses a different format for its elytra, which would require adapting the whole mod and textures for it.
