### ISSUE TITLE
[Bug]: Opening Config In Mod Menu Crashes The Game

### ISSUE THREAD

**Issue by renatocs81** [Kikugie/elytra-trims#54]
### Mod loader

Fabric

### Minecraft version

1.20.1

### Mod version

3.0.0 (Without Extension)

### Affected mods

- [X] Elytra Trims
- [ ] Extensions

### Bug description

I don't know what I should write as the description, but I still have something to say.
### Steps to reproduce

1. Open Mod Menu After Game Loading
2. Click On Elytra Trims Mod
3. Click On Config
4. **### Crash**

### Relevant logs

I don't think I know which one is the correct crash log, so there will be none.

**Comment by kikugie** [comment]
Please send the log (after it crashes, go to `.minecraft/logs/latest.log`), because I can't reproduce the issue.

**Comment by renatocs81** [comment]
I still don't know what is the correct crash log, but I believe the mod menu mod I used was named Catalogue.
The crash log/report probably might be: crash-2024-04-29_18.01.18-client.txt.
Could you see that entire crash log/report to see if you know what the problem is (If you know how to get access to the txt. file)?
The crash log/report you saw on the comment might be the incorrect one but I'm not sure.
also ignore the 3 random hashtags
and oh my god this comment is so long

**Comment by renatocs81** [comment]
also i dont think i feel like changing the config anymore

**Comment by kikugie** [comment]
That was almost right. Just drag the file into github message box and send

**Comment by renatocs81** [comment]
Sorry, but the latest.log file has now changed so the issue can no longer be solved, or can it?
How I can (probably) make you resolve the issue is:
1. I can delete all the crash log/reports
2. I can crash the game again by doing the exact same thing as in this issue.
3. I can give you the new log/report.
Mods:
Abuseless Hardcore
Aileron
Anvil Repairing
Architectury API
Armor Statues
Balm
Better Third Person
BHMenu
Bleached
Bookshelf
Borderless Mining
Catalogue (Main Mod)
Chunks Fade In
Classic Sword Blocking
Clean Tooltips
Cloth Config API
Collective
Conduits Prevent Drowned
Controlling
Convenient Name Tags
Couplings
Craft Presence
Cupboard
Custom default World Preset
Disable New World Screen
Distant Friends
dragonfight-fabric-1.20.1-4.4.jar
Elytra Trims (Main Mod 2)
Entity Model Featuress
Entity Texture Features
Entity Culling
ESO
Exposure
Fabric API (Main Mod 3)
End Remastered
Fabric Language Kotlin
Fabric Seasons
Falling Leaves
Faux Custom Entity Data
Ferrite Core
Forge Config API Port
From The Fog
Global Packs
Golden Age Combat
Item Highlighter
High Speed Rail (camman18's dream)
Cascades/Hybrid
Iceberg
Indium
Independent Pets
Inventory Hud+
Iris
Item Obliterator
Jade
JourneyMap
Konkrete
KubeJS
LambDyanmic Lights
Let Me Despawn
Library Ferret
Lithium
LootJS
Melody
Mending Over Time
Menulogue
Modern Beta
Mod Menu
Moonlight
More Banner Features
MoreJS
Mouse Wheelie
Necronomicon API
Nemo's Blooming Blossom
Nether Portal Fix
NiftyCarts
No XP Anvils
No Chat Reports
Nostalgic Tweaks
No Telemetry
Nvidium
Old MC Logo
Open Parties And Claims
OWO Lib
Playlist
Polytone
ProbeJS
Puzzles Lib
Rail Destinations
Realistic Fire Spread
Reese's Sodium Options
Resourceful Config
Resourceful Lib
Rhino
Roughly Enough Items
Searchables
Season HUD
Server Country Flags
Sleep Tight
Sniffer+
Sodium Extra
Sodium
Sound Physics Remastered
Spyglass Improvements
Terrestria
TL Skin and Cape
Trampling
Useful Spyglass
vcinteraction-fabric-1.20.1-1.0.6
Villager Config
Simple Voice Chat
Wandering Collector
YetAnotherConfigLib
YOSBR/Your Options Shall Be Respected
Zoomify
Rare Ice
cAN i mINe tHIs bLoCK?
This Is So Much Mods To Deal With.

**Comment by kikugie** [comment]
It should work with YetAnotherConfigLib, but with its version 3.0+, make sure you have the latest one.  
Also apparently the crash is an issue with Menulogue implementation, I've already reported it to the mod author.

**Comment by renatocs81** [comment]
It got fixed out of nowhere, so now I'm in peace :).
