### ISSUE TITLE
[Bug]: Servers require client side mod installation on 1.20.5+

### ISSUE THREAD

**Issue by sternschnaube** [Kikugie/elytra-trims#56]
### Mod loader

Fabric

### Minecraft version

1.20.6

### Mod version

3.1.4

### Affected mods

- [X] Elytra Trims
- [ ] Extensions

### Bug description

![image](https://github.com/kikugie/elytra-trims/assets/120551916/2d4446ec-afcd-48e0-ac99-38cfddecfc7b)

Received unknown remote registry entries from server
Registry entry (minecraft:crafting_special_elytrapatterns) is missing from local registry (minecraft:recipe_serializer)
Registry entry (minecraft:crafting_special_elytraglow) is missing from local registry (minecraft:recipe_serializer)
Registry entry (minecraft:crafting_special_elytraanimation) is missing from local registry (minecraft:recipe_serializer)

**Comment by kikugie** [comment]
Seems like your server has `requireClientSide` option enabled, in which case it is an expected error.

**Comment by sternschnaube** [comment]
Using the new generated config, in which this option is from the beginning disabled.

{"addGlow":true,"cleanableElytra":true,"requireClientSide":false,"addTrims":true,"addPatterns":true}

**Comment by kikugie** [comment]
Please verify that it's not affected by any other mods you have. I can't reproduce it with a local server running elytra trims 3.1.4 and a fully vanilla client: 
![image](https://github.com/kikugie/elytra-trims/assets/50152507/d6b301f7-1f67-415a-9bb7-9a5fe85e84d8)

**Comment by sternschnaube** [comment]
The issue is the Fabric API itself. Very weird, vanilla connects without problems. If Fabric API is present on the client, the problem occurs.

**Comment by kikugie** [comment]
Weird indeed, I'll look into it later today

**Comment by sternschnaube** [comment]
Maybe it's related with this.

![image](https://github.com/kikugie/elytra-trims/assets/120551916/6163456c-11c6-4059-9e06-64ced2843a9e)

**Comment by kikugie** [comment]
This is gonna be more work than I anticipated, blame 1.20.5

**Comment by kikugie** [comment]
Ok, it was less work than I reanticipated

**Comment by sternschnaube** [comment]
I'm glad to hear that 😄

**Comment by kikugie** [comment]
# [FIXED](https://modrinth.com/mod/elytra-trims/version/cmwGwY3i)
![cat-agree](https://github.com/kikugie/elytra-trims/assets/50152507/a103215f-ba2f-4552-b865-ec14e9dfea2d)

**Comment by electricsteve** [comment]
It's happening again
![image](https://github.com/user-attachments/assets/c05d8a0e-092b-40e1-9631-35dd6fde0e87)
Server mod version: 3.5.0+1.21
Client without mod can't join, clients with can.
I will disable the mod on the server for now because we don't have elytras yet, but please fix this.
EDIT: Mc version is 1.21

**Comment by kikugie** [comment]
Please use version 3.4.4 for the time being

**Comment by electricsteve** [comment]
So is this fixed now?

**Comment by kikugie** [comment]
In 3.5.1
