### ISSUE TITLE
[Bug]: Incompatibility with First-Person Model

### ISSUE THREAD

**Issue by peow** [Kikugie/elytra-trims#58]
### Mod loader

Fabric

### Minecraft version

1.20.1

### Mod version

3.1.5

### Affected mods

- [X] Elytra Trims
- [ ] Extensions

### Bug description

when using the Elytra Trims together with the First-Person Model, when holding an Elytra in your hand the head of your skin disappears

![2024-05-12_21 52 39](https://github.com/kikugie/elytra-trims/assets/105888751/0b5b99a2-993d-4752-9b9a-7a396770856c)

![2024-05-12_21 52 42](https://github.com/kikugie/elytra-trims/assets/105888751/d122ca10-681a-4eee-987d-948c9ef4efc3)

*since Minecraft doesn't refresh a model while you're viewing the model, you need to exit F5 and come back to see that your head is gone*

-----------

First-Person Model usually disables the rendering of some part of the body when it detects that this will hinder the first-person view, I imagine that something in the Elytra Trims has made First-Person Model think that the Elytra in the hand would be equipped in the head or something similar, idk

the problem stops when you press F6 to disable First-Person Model

----------

I'm using Fabric 1.20.1, First-Person Model 2.3.4
![2024-05-12_22 01 54](https://github.com/kikugie/elytra-trims/assets/105888751/b12b84ba-d1a3-4129-a2a5-efc3749e5f90)

mod link: https://modrinth.com/mod/first-person-model

-------

if is possible to fix this pls make an update to **Fabric 1.20.1**, thanks

### Steps to reproduce

1. Install Elytra Trim (+dependencies)
2. Install First-Person Model
3. Select a Elytra in the hotbar and press F5

### Relevant logs

I don't think the log is necessary, but in case I'm wrong: https://mclo.gs/KkaRM89

**Comment by kikugie** [comment]
~~Congratulations on discovering a hidden bug I totally wasn't aware of~~, but on a serious note i don't know. It also can make your head reappear in 3rd person just as magically and the mods don't have any code interacting with each other.  
So I'll leave this open for now, and as a temp fix you can disable the elytra model in the mod config.

**Comment by peow** [comment]
i will show the issue to the First-Person model dev

**Comment by kikugie** [comment]
I've found a solution that should fix both issues, but it definitely needs some tinkering with the model positioning:
![2024-05-13_22 47 09](https://github.com/kikugie/elytra-trims/assets/50152507/313e8ce2-f0af-4dbe-bf59-574177ce2b9f)

**Comment by kikugie** [comment]
![too sticker](https://github.com/kikugie/elytra-trims/assets/50152507/c3f9d51d-4874-41b3-aebb-5982570fa1f1)

**Comment by peow** [comment]
xd, good luck

**Comment by kikugie** [comment]
The fixes are done. I want to see if I can check off some other known bugs off the list and test other mc versions before publishing.  
Here's the current build of the mod, so you don't have to wait: 
[elytratrims-fabric-3.1.6-bugfix+1.20.1.zip](https://github.com/kikugie/elytra-trims/files/15305190/elytratrims-fabric-3.1.6-bugfix%2B1.20.1.zip) (extract the file because gh doesn't allow .jar)

**Comment by peow** [comment]
one question: is it possible to prevent the Elytra from overlapping with the hotbar frame?

![image](https://github.com/kikugie/elytra-trims/assets/105888751/2e4c39d0-34b5-4607-b3ee-64056ea7d74a)
![image](https://github.com/kikugie/elytra-trims/assets/105888751/b8ca74a5-6713-4376-83fe-419448bc344a)

**Comment by kikugie** [comment]
I tweaked it a bit for the next update 
![image](https://github.com/kikugie/elytra-trims/assets/50152507/206da9b2-8fc2-4975-bf43-3f580ffdd383)

**Comment by peow** [comment]
show me the hotbar pls

**Comment by kikugie** [comment]
![image](https://github.com/kikugie/elytra-trims/assets/50152507/e8b8c87a-79df-42cc-b8a1-c6df31085ab7)

**Comment by peow** [comment]
epic

**Comment by peow** [comment]
First-Person Model mentioned u on his discord server, just so you know

**Comment by kikugie** [comment]
I am aware lol
