### ISSUE TITLE
[Bug]: Game crash on loading title menu

### ISSUE THREAD

**Issue by SageofTurtles** [Kikugie/elytra-trims#59]
### Mod loader

Fabric

### Minecraft version

1.20.1

### Mod version

3.1.7 (Fabric)

### Affected mods

- [X] Elytra Trims
- [ ] Extensions

### Bug description

As best I can tell, there seems to be some incompatibility with the Create mod, and possibly other mods in my pack, that cause the game to crash as soon as it attempts to load the buttons on the title menu at startup.  The crash log (attached) mentions "goggles", so I'm assuming it's a rendering issue with the goggle item icon, as one of the buttons on the title menu displays that item icon with Create installed.

### Relevant logs

https://mclo.gs/9xD8F2N

**Comment by captinwill** [comment]
same except on forge fix this bug

**Comment by kikugie** [comment]
Release will be later, I'm busy

**Comment by katubug** [comment]
Came to report same issue. Thank you for working on this! I will downgrade to previous version for now :)

**Comment by kikugie** [comment]
I've included a change that should prevent it from crashing, but I can't reproduce with Trinkets and Create. Pls test if this works fine with your mod sets.  
[ET-3.1.8-testing.zip](https://github.com/kikugie/elytra-trims/files/15382129/ET-3.1.8-testing.zip) (has fabric & forge 1.20.1 builds)

**Comment by katubug** [comment]
Forge version worked for me!

**Comment by kikugie** [comment]
![](https://media1.tenor.com/m/_FEDJkpMWQAAAAAC/pot-of-greed.gif)
Update tomorrow then
