### ISSUE TITLE
Cannot Dye In Server

### ISSUE THREAD

**Issue by Kroxywuff** [Kikugie/elytra-trims#6]
Hi, 

I'm running this on my fabric server and for some reason I can't dye elytra or make them glow. I can craft trims on them just fine so I know the mod is functioning. I have the mod installed on my client and the server.

On single player everything works fine, which is what is confusing me.

**Comment by kikugie** [comment]
This has been previously addressed, make sure you have the latest version of the mod installed on the server.

**Comment by Kroxywuff** [comment]
The server and myself are both running 1.1.8

**Comment by kikugie** [comment]
Oh, I've found the issue and will push the update later today. For now you
can install version 1.1.5 on the server.
