### ISSUE TITLE
[Bug]: Incorrect Elytra Render in Item Frame

### ISSUE THREAD

**Issue by peow** [Kikugie/elytra-trims#60]
### Mod loader

Fabric

### Minecraft version

1.20.1

### Mod version

3.1.8

### Affected mods

- [X] Elytra Trims
- [ ] Extensions

### Bug description

when placing an Elytra (with Use Elytra Model ON) in the Item Frame it renders incorrectly, appearing inside the wall

![2024-05-27_21 43 21](https://github.com/kikugie/elytra-trims/assets/105888751/610e7687-073e-454f-a13a-b8c2651beb2d)

![2024-05-27_21 43 31](https://github.com/kikugie/elytra-trims/assets/105888751/42bc3826-9f5f-4485-a682-6a2c0f22ff82)

**Comment by peow** [comment]
check this texture pack
https://modrinth.com/resourcepack/elytra-display

**Comment by kikugie** [comment]
The model is too big there, so won't be like that

**Comment by peow** [comment]
I know, but it's pretty cool
