### ISSUE TITLE
asymmetrical customization?

### ISSUE THREAD

**Issue by 6xolotl** [Kikugie/elytra-trims#64]
### Description

i love this mod and all the different customization options it has to offer. it really adds some spice to the otherwise bland appearance of the elytra, especially with all the modded trim compatibilities! the ability to make asymmetrical wings would be a perfect cherry on top, kind of like how CE has a system to split elytra into two wings for separate customization, although obviously ET would probably take a different approach to the idea.

apologies if this is considered rude in any way, i dont know modding culture so i dont know if this would be seen as "ripping off" the person who made CE, but imo the idea of asymmetrical wings is way too cool to only be in one mod.

completely understand if this isnt a feature youre interested in adding, but i thought it was worth a try to suggest it. have a lovely day!

**Comment by kikugie** [comment]
CE adds asymmetrical customisation by completely replacing the elytra item, model and how it's rendered, while ET focuses on more vanilla-like and mod compatible approach.  
Implementing it would sacrifice some of the compatibility and go against the design principles of ET.

**Comment by 6xolotl** [comment]
> CE adds asymmetrical customisation by completely replacing the elytra item, model and how it's rendered, while ET focuses on more vanilla-like and mod compatible approach. Implementing it would sacrifice some of the compatibility and go against the design principles of ET.

ah, i see! thank you for the answer regardless, have a nice day! :]
