### ISSUE TITLE
[Bug]: Wrong Posed Model View

### ISSUE THREAD

**Issue by Fyoncle** [Kikugie/elytra-trims#65]
### Mod loader

Fabric

### Minecraft version

1.20.1

### Mod version

3.2.0

### Affected mods

- [X] Elytra Trims
- [ ] Extensions

### Bug description

![image](https://github.com/kikugie/elytra-trims/assets/63975256/a78ca318-f503-45a3-9e6a-b0e2c08dcb41)
Elytra models looking weird when first placed on a smithing table or taken to hand, not sure if this because of Elytra Trims mod since i didn't try it with only Elytra Trims mod, i am using Elysium Days 3.5.0 Modpack

### Steps to reproduce

1. Install Latest Release Of Elysium Days
2. Update Elytra Trims To 3.2.0
3. Take a Elytra from Creative (see model wrong for few seconds when holding then it fixes itself automatically)
4. Put in a smithing table and put your trim and stuff
5. See the elytra shape being all plain instead of elytra opens wings
![image](https://github.com/kikugie/elytra-trims/assets/63975256/93764082-3c87-4cf1-b33f-1e5b9d25f729)
![image](https://github.com/kikugie/elytra-trims/assets/63975256/1f45c62b-9bc4-4abb-98f9-f820e0b488a2)
Then a few seconds later it fixes itself

### Relevant logs

https://mclo.gs/47haexn

**Comment by kikugie** [comment]
It doesn't happen in Elytra Trims on itself, so it's a mod compatibility issue. I can't test it by manually copying each of your 400 mods, so please narrow it down.

**Comment by Fyoncle** [comment]
> It doesn't happen in Elytra Trims on itself, so it's a mod compatibility issue. I can't test it by manually copying each of your 400 mods, so please narrow it down.

Oh... :(

**Comment by Fyoncle** [comment]
Okay then, ill binary search and return back.

**Comment by Fyoncle** [comment]
So, it only happens normal worlds i guess, but when you open a void world, it loads the elytra thing so fast that its impossible to see any difference or the glitch, i tried some things but didn't been able to fix it.

**Comment by kikugie** [comment]
Referencing https://github.com/kikugie/elytra-trims/issues/66#issuecomment-2170545601 I can reproduce it with Fresh Moves, in which case it's on the resourcepack's side. Elytra Trims doesn't change how elytra is animated. For the smithing table it just equips the item on the armor stand.

**Comment by Fyoncle** [comment]
> Referencing [#66 (comment)](https://github.com/kikugie/elytra-trims/issues/66#issuecomment-2170545601) I can reproduce it with Fresh Moves, in which case it's on the resourcepack's side. Elytra Trims doesn't change how elytra is animated. For the smithing table it just equips the item on the armor stand.

Eh i think its more likely EMF ETF's problem then, but ill let the Fresh Moves devs know too.

**Comment by kikugie** [comment]
I suppose the latter. It doesnt happen without the Fresh Moves pack. And in case, fortunately this fixes itself quickly.

**Comment by Fyoncle** [comment]
> I suppose the latter. It doesnt happen without the Fresh Moves pack. And in case, fortunately this fixes itself quickly.

But Fresh Moves uses the possibilities of EMF ETF, not only Fresh Moves but every other pack that activates EMF ETF will also cause this, so i think perfect place to report this is traben!

**Comment by kikugie** [comment]
I guess won't hurt. But it's the Player Moves pack controlling the elytra position

**Comment by Fyoncle** [comment]
> I guess won't hurt. But it's the Player Moves pack controlling the elytra position

Well reported to both sides xD lets see who fixes the issue first :)

**Comment by Fyoncle** [comment]
Also how the hell did you do the easter egg? i checked source code for infinite whiles and tried infinite combinations, how the hell to make the easter egg work lol, i saw it bad apple easter egg

**Comment by kikugie** [comment]
What infinite whiles?
Also the bad apple one just has an animated texture.

**Comment by Fyoncle** [comment]
> What infinite whiles? Also the bad apple one just has an animated texture.

Infinite hours basically lmao, but how to activate bad apple inside the game?

**Comment by kikugie** [comment]
You literally combine it with a bad and an apple.

**Comment by Fyoncle** [comment]
> You literally combine it with a bad and an apple.

A "bad"...? what is a bad.

**Comment by kikugie** [comment]
Find out :P

**Comment by Fyoncle** [comment]
> Find out :P

Evil :(

**Comment by Fyoncle** [comment]
> Find out :P

Combine in what exactly... smithing table? Atleast give a hint of that!

**Comment by kikugie** [comment]
Naturally crafting. If you're really desperate, look through the source code, but that kinda ruins the point of it being an easter egg.

**Comment by Fyoncle** [comment]
> Naturally crafting. If you're really desperate, look through the source code, but that kinda ruins the point of it being an easter egg.

I did check the whole source code, nothing else there :v

**Comment by kikugie** [comment]
The recipe is hardcoded so iono bad reading skills

**Comment by Fyoncle** [comment]
> The recipe is hardcoded so iono bad reading skills

:c

**Comment by kikugie** [comment]
||https://github.com/kikugie/elytra-trims/blob/kotlin/src/main/kotlin/dev/kikugie/elytratrims/common/recipe/ETAnimationRecipe.kt ||

**Comment by Fyoncle** [comment]
> ||https://github.com/kikugie/elytra-trims/blob/kotlin/src/main/kotlin/dev/kikugie/elytratrims/common/recipe/ETAnimationRecipe.kt ||

![image](https://github.com/kikugie/elytra-trims/assets/63975256/8325b67d-5e58-4632-b055-7a1fa3addaa1)
Um... isn't it meant to be animated...?

**Comment by kikugie** [comment]
400 mods be like

**Comment by Fyoncle** [comment]
> 400 mods be like

:(

**Comment by Traben-0** [comment]
If its caused by fresh moves animations, then there is nothing that can be done really :/

though you could variate the model by the entity type wearing them and ensure the default non-animated model loads for armor stands

**Comment by kikugie** [comment]
Same as #66
