### ISSUE TITLE
[Bug]: Dye Color Flashing With Elytra

### ISSUE THREAD

**Issue by Fyoncle** [Kikugie/elytra-trims#66]
### Mod loader

Fabric

### Minecraft version

1.20.1

### Mod version

3.2.0

### Affected mods

- [X] Elytra Trims
- [ ] Extensions

### Bug description

It's just flashing when i move around.

https://github.com/kikugie/elytra-trims/assets/63975256/b08ae06a-7358-4a5e-bf35-e3544f121e80

### Steps to reproduce

1. Enter the world
2. Dye a elytra (i dyed it black)
3. See it flashing when moving around or rotating the screen in specific places

### Relevant logs

https://mclo.gs/jHN6pT5

**Comment by Fyoncle** [comment]
After some time it disappears forever and only way to bring it back to pause the game and resume again, if not works, to open elytra model on config for some reason.

**Comment by kikugie** [comment]
Again, don't just report any issue with so many mods.  
I am not going to go through the entire list, looking up each mod on modrinth, installing it and only then working out which one is causing it. So in this state the issue will simply be marked as invalid and closed.  
When you have an issue with a mod, do the following:
1. Install the problematic mod and its required dependencies. If the issue occurs, go report.
2. Test with fewer mods and find the smallest combination of mods causing the issue. Report and list those mods.

**Comment by Fyoncle** [comment]
So i have to binary search i guess?

**Comment by Fyoncle** [comment]
Also seems like reason is EMF & ETF mod duo

**Comment by kikugie** [comment]
I'm playing on 1.20.1 with ET, EMF and ETF and it doesn't happen. Did you test with *only* ET, ETF and EMF installed?

**Comment by Fyoncle** [comment]
> I'm playing on 1.20.1 with ET, EMF and ETF and it doesn't happen. Did you test with _only_ ET, ETF and EMF installed?

Not only EMF ETF installed, you need a thing that uses EMF ETF and changes your player model, like the Fresh Moves resource pack, if not, EMF ETF wont override your player settings.

**Comment by Fyoncle** [comment]
Hey hey hey kikugie, Fresh Moves was the issue, they got a file that animates elytra which is for making elytra follow the character animations, and when i remove the file, heres the result:
![image](https://github.com/kikugie/elytra-trims/assets/63975256/e9645b91-17d1-4cea-8977-972a56e3ef13)

Not sure about is other issue caused by Fresh Moves or not, but this one definetely is.

**Comment by Traben-0** [comment]
does this occur with a default elytra.jem exported by EMF? or only with an animated custom one like in fresh moves?

**Comment by Fyoncle** [comment]
> does this occur with a default elytra.jem exported by EMF? or only with an animated custom one like in fresh moves?

If Fresh Moves's elytra.jem removed, this problem won't occur anymore.

**Comment by kikugie** [comment]
Marking as wontfix since it's a Fresh Moves' issue.

**Comment by Fyoncle** [comment]
> Marking as wontfix since it's a Fresh Moves' issue.

Sad ;(

**Comment by Fyoncle** [comment]
@kikugie 
This issue has been fixed by EMF ETF's last update as far as i see
![image](https://github.com/kikugie/elytra-trims/assets/63975256/e62d5f18-ea8c-4bb6-bec5-6a3a2a66e68e)
