### ISSUE TITLE
[Bug]: Additional Trims incompatibility

### ISSUE THREAD

**Issue by cotona4** [Kikugie/elytra-trims#68]
### Mod loader

Forge

### Minecraft version

1.20.1

### Mod version

3.2.0

### Affected mods

- [ ] Elytra Trims
- [X] Extensions

### Bug description

 It is not compatible with the next mods: (Upgraded Additional Trims,Upgraded Trims,Additional Trims) the game, it closes at startup and the text is replaced with 00000, I already confirmed no compatibility when I remove it, it merges normally

### Steps to reproduce

1.install (Additional Trims and elytra trips)
2.the game crashed

### Relevant logs

https://mclo.gs/xfOIfqJ

**Comment by kikugie** [comment]
Pretty sure it's a fail on the Additional Trims' (and others) side, since the same process works fine with other mods, but can't check it rn because those mods are closed source.

**Comment by cotona4** [comment]
thank you very much it worked for me
