### ISSUE TITLE
[Bug]: 3.3.0 Breaks with sinytra and bclib

### ISSUE THREAD

**Issue by mxnmnm** [Kikugie/elytra-trims#69]
### Mod loader

NeoForge

### Minecraft version

1.20.1

### Mod version

3.3.0

### Affected mods

- [X] Elytra Trims
- [ ] Extensions

### Bug description

Elytra Trims crashes when I use 3.3.0 in my modpack. It works on 3.2.0 and older versions. It looks like something having to do with bclib and sinytra connector. If you need more info let me know but hopefully the crash report has all you need to know.

### Relevant logs

https://gist.github.com/mxnmnm/70ce017c4068b0d55b651e495247c64e

**Comment by kikugie** [comment]
I'm unable to reproduce the issue with the following mods, so it is possible for bclib to conflict with some of your mods on itself.
![image](https://github.com/kikugie/elytra-trims/assets/50152507/22a46fc4-ceab-4042-b25f-838ab16c84da)

**Comment by mxnmnm** [comment]
Ok somehow it works now with 0 changes so I guess we're good
