### ISSUE TITLE
Incompatible with armor trim materials from the Cinderscapes mod

### ISSUE THREAD

**Issue by Diego13303** [Kikugie/elytra-trims#7]
## Description
Trying to trim Elytras with ores from the mod Cinderscapes shows a missing texture in the Smithing Table and no difference from an untrimmed Elytra in-game
![image](https://github.com/kikugie/elytra-trims/assets/91715852/1ebf9884-edbb-4d98-8e02-e0e56fdc49e5)
![image](https://github.com/kikugie/elytra-trims/assets/91715852/b46c7312-b6e1-43c9-a6be-10019592cb2c)

## To Reproduce

1. Put an Elytra and an armor trim in a Smithing Table
2. Attempt to use Rose Quartz, Smoky Quartz or Sulfur Quartz from Cinderscapes as the trimming material
3. Preview on Smithing Table displays as missing texture
4. Grab the trimming result

What you expect to see: The Elytra with the correct trimming

What actually happens: I get an Elytra with tooltips indicating it´s been trimmed, but visually it looks the samed as an untrimmed one

## Environment
Describe the environment to reproduce this bug:

- Minecraft version: 1.20.1
- Elytra Trims version: 1.1.9
- Cinderscapes version: 4.0.5

**Comment by kikugie** [comment]
It doesn't restrict trim patterns to ones with available textures to allow resourcepack support (Which [Elytra Trims Extensions](https://modrinth.com/mod/elytra-trims-extensions) relies on). And to show that it intentionally has magenta/black texture in the smithing table, but none in the world to not ruin the look.

Compatibility won't be added to the main mod, but I'll work on adding it to the extensions.

**Comment by Diego13303** [comment]
Oh I see! So is Elytra Trims Extensions just Resource packs then?

**Comment by kikugie** [comment]
Yea, its a bundle of resourcepacks, with an idea that it would be more convenient to download one mod than a bunch of separate resourcepacks

**Comment by Diego13303** [comment]
I see! I´ll wait for it to be updated to add support for Cinderscapes then. Thank you so much for the quick reponse!

**Comment by kikugie** [comment]
Cinderscapes only adds new materials, so its the same issue as #10.  
1.1.10-beta fixes the broader issue, providing support for any new material. Its still experimental, so please create a new issue report for it if needed.
