### ISSUE TITLE
[Bug]: remaining incompatibilities with Butterfly Elytra from the Clutter mod

### ISSUE THREAD

**Issue by peow** [Kikugie/elytra-trims#71]
### Mod loader

Fabric

### Minecraft version

1.20.1

### Mod version

3.4.0

### Affected mods

- [X] Elytra Trims
- [ ] Extensions

### Bug description

the trimmed Butterfly Elytras (fixed in the last update) are interesting, but the mod needs to block Butterfly Elytras from being colored and banners from being added to them

because when you dye it, it loses all its texture, and when you put the banner on it, the banner also covers all its texture

------

* coloring:
![image](https://github.com/kikugie/elytra-trims/assets/105888751/1035c606-79af-42d8-a6ad-10fed3fc67a1)
![2024-07-09_12 47 54](https://github.com/kikugie/elytra-trims/assets/105888751/7e99bfc2-28ec-43aa-879c-ea90ed6dd5f1)

* adding banner:
![image](https://github.com/kikugie/elytra-trims/assets/105888751/977447d7-5e12-4a67-be86-27ad2fcde1d2)
![2024-07-09_12 48 18](https://github.com/kikugie/elytra-trims/assets/105888751/b3c3089a-f5a2-4904-b9a1-cb01ba026a45)

-----------

besides, as the Butterfly Elytra is smaller than the Vanilla Elytra, there are some visual problems, for example the cloud renders on top of Butterfly Elytra with banner

* Butterfly Elytra without modifications:
![image](https://github.com/kikugie/elytra-trims/assets/105888751/3ece81e6-9dbb-4524-a5ee-b710ae2afc36)

* Butterfly Elytra with banner applied on it
![image](https://github.com/kikugie/elytra-trims/assets/105888751/ea003ea6-4559-4431-ac20-23e1265bec4e)

-----------------

by preventing the Butterfly Elytra from being colored and applying banners to it, these problems would be solved

### Steps to reproduce

1 - Install Elytra Trims
2 - Install Clutter
3 - modify a Butterfly Elytra (coloring/adding banner)

**Comment by kikugie** [comment]
Colored textures use the base elytra model as the reference, which is why custom shaped elytras look wrong.  
I won't disable any features for any mod by design, so if you don't like how that looks - don't apply dyes and banners yourself.  

Apart from that, the issue is of the same nature as #63, so I'll mark it as duplicate.

**Comment by kikugie** [comment]
You need https://modrinth.com/mod/elytra-trims-extensions for More Armor Trims support.

**Comment by peow** [comment]
> don't apply dyes and banners yourself.
I'm imagining the possibility of some user trying to modify a modded Elytra and realizing that it didn't work, then he comes to bother you asking why it's not working

if you don't want to disable any feature for any mod, at least allow it to be possible to remove the modifications by using the cauldron with water, currently only the Vanilla Elytra can be "cleaned", modded Elytras cannot.

https://github.com/kikugie/elytra-trims/assets/105888751/2a9496df-a135-409f-a984-4bba6633ac27

testing with Clutter and BetterEnd

**Comment by kikugie** [comment]
Added cauldron cleaning in 3.4.1
