### ISSUE TITLE
[Bug]: Missing More Armor Trims Textures

### ISSUE THREAD

**Issue by Proxi2** [Kikugie/elytra-trims#72]
### Mod loader

Fabric

### Minecraft version

1.21

### Mod version

3.4.0

### Affected mods

- [X] Elytra Trims
- [ ] Extensions

### Bug description

When combined with the More Armor Trims mod the armor trims don't work. According to the logs it can't find the texture at all. If I understand correctly, the extensions to support this and other mods are supposed to be merged into the base mod right?

### Steps to reproduce

1. Install Elytra Trims, Fabric API, Fabric Language Kotlin, and More Armor Trims
2. Start game
3. Logs will warn about missing textures for the More Armor Trims on elytra
4. Load into world
5. Put a trim on an elytra (it will have a missing texture in the smithing table preview)
6. The elytra will not have the trim and will also output another warning about not having whatever trim and material you chose

### Relevant logs

https://mclo.gs/ccNjBZW

**Comment by kikugie** [comment]
You need https://modrinth.com/mod/elytra-trims-extensions for More Armor Trims support.

**Comment by Proxi2** [comment]
Okay my bad then I misunderstood. I thought it was merged into the main mod. Is there an ETA for 1.21 update for that

**Comment by kikugie** [comment]
At now, it is version-independent
