### ISSUE TITLE
[Bug]: Trims not appearing on Elytra when put into the cape slot with the Elytra Trinket mod

### ISSUE THREAD

**Issue by RepeatSwitch** [Kikugie/elytra-trims#75]
### Mod loader

Fabric

### Minecraft version

1.21

### Mod version

Elytra Trims (3.4.1), Elytra Trinket (1.0.9)

### Affected mods

- [X] Elytra Trims
- [X] Extensions

### Bug description

While having both mods installed you can apply the armor trims without issue and they also display onto the equipped elytra when it is put into the chestpiece slot but not with the cape slot,

### Steps to reproduce

1. Install Fabric Loader (v0.16.0) and Fabric API (v0.100.7+1.21) on Minecraft 1.21
2. Install both mods + All dependencies
3. Apply trims to elytra
4. When equipped to cape slot no trims visible but are on armor slot
![Screenshot 2024-07-16 030824](https://github.com/user-attachments/assets/3e356be7-a689-4a5f-b650-166efa2be326)
![Screenshot 2024-07-16 030703](https://github.com/user-attachments/assets/90a09ca3-cde1-4ae6-a90e-bf7b1d8331c8)
![Screenshot 2024-07-16 030803](https://github.com/user-attachments/assets/6bcd41b5-48b3-44d0-b8b1-2e1d5a338be0)

**Comment by kikugie** [comment]
Published 3.4.2

**Comment by Yuchenjimmy** [comment]
### Mod loader
Fabric

### Minecraft version
1.21

### Mod version
Elytra Trims (3.4.2), Elytra Slot (9.0.0)

### Bug description
I think this is somehow related so I decided not to open a new one. BTW, the trims are not glowing in Nostalgia VX but it can glow in BSL, may I ask is it a shader problem or a mod problem?

### Steps to reproduce

1. Install Fabric Loader (v0.16.0) and Fabric API (v0.100.7+1.21) on Minecraft 1.21
2. Install both mods + All dependencies
3. Apply trims to elytra
4. When equipped to cape slot no trims visible but are on armor slot

### Screenshots
![Minecraft_ 1 21 - Multiplayer (3rd-party Server) 2024_7_18 下午 11_42_07](https://github.com/user-attachments/assets/93a8e012-9ef6-43a1-bc33-c00f61ca1b05)
![Issues · kikugie_elytra-trims - Google Chrome 2024_7_18 下午 11_42_46](https://github.com/user-attachments/assets/04f7892a-8935-46d2-9ac6-0817b3312ea7)
![Minecraft_ 1 21 - Multiplayer (3rd-party Server) 2024_7_18 下午 11_42_54](https://github.com/user-attachments/assets/8e42f0d0-3d06-4b7b-b8f2-c139ea63d2d4)

**Comment by kikugie** [comment]
At the time of the 3.4.2 release, Elytra Slot was not updated to 1.21, so the compatibility was done preemptively, based on how other mods do it. But they decided to do it differently, which ofc needs a fix.
