### ISSUE TITLE
[Bug]: Error with rendering 3d item model on Complementary

### ISSUE THREAD

**Issue by Gsimken** [Kikugie/elytra-trims#76]
### Mod loader

Fabric

### Minecraft version

1.21

### Mod version

3.4.3

### Affected mods

- [X] Elytra Trims
- [ ] Extensions

### Bug description

3D MODEL ITEM (Use elytra model config)
![image](https://github.com/user-attachments/assets/6c81cc85-46c6-42e0-9109-4748788e0add)
![image](https://github.com/user-attachments/assets/127b5931-40ea-447d-bf06-a366ca2efe37)
 Not Using elytra model config
![image](https://github.com/user-attachments/assets/8fd56213-d0a3-414d-95bb-56e10ed155c6)

Weird texture 

**Mods installed**

- carpet-extra-1.21-1.4.147.jar
- cloth-config-15.0.127-fabric.jar
- collective-1.21.0-7.67.jar
- coordfinder-fabric-1.21-1.1.0.jar
- elytratrims-fabric-3.4.3+1.21.jar
- entity_model_features_fabric_1.21-pre3-test.jar
- entity_texture_features_fabric_1.21-6.1.2.jar
- Essential-fabric_1-21.jar.disabled
- EuphoriaPatcher-0.3.4-fabric.jar
- fabric-api-0.100.4+1.21.jar
- fabric-carpet-1.21-1.4.147+v240613.jar
- fabric-language-kotlin-1.11.0+kotlin.2.0.0.jar
- indium-1.0.33+mc1.21.jar
- inventoryhud.fabric.1.21-3.4.22.jar
- InventorySorter-1.9.0-1.21.jar
- inventorytotem-1.21.0-3.2.jar
- iris-1.7.1+mc1.21.jar
- itemscroller-fabric-1.21-0.23.999-sakura.2.jar
- Jade-1.21-Fabric-15.1.0.jar
- journeymap-fabric-1.21-6.0.0-beta.12.jar
- libjf-3.16.0.jar
- lista.txt
- litematica-fabric-1.21-0.18.999-sakura.11.jar
- lithium-fabric-mc1.21-0.12.7.jar
- malilib-fabric-1.21-0.19.999-sakura.4.jar
- malilib-fabric-1.21-0.19.999-sakura.6.jar
- minihud-fabric-1.21-0.31.999-sakura.8.jar
- modmenu-11.0.1.jar
- nvidium-0.2.8-beta.jar
- Ping-Wheel-1.9.1-fabric-1.21.jar
- recast-1.21.0-3.4.jar
- replantingcrops-1.21.0-5.3.jar
- respackopts-4.10.0.jar
- scaffoldingdropsnearby-1.21.0-3.2.jar
- servux-fabric-1.21.0-0.2.0.jar
- sodium-fabric-0.5.9+mc1.21.jar
- syncmatica-fabric-1.21-0.3.12-sakura.4.jar
- toggleableitemframes-5.0.0-1.21.jar
- tweakeroo-fabric-1.21-0.20.999-sakura.8.jar
- whereisit-2.5.0+1.21.jar
- YetAnotherConfigLib-3.5.0+1.21-fabric.jar

### Steps to reproduce

With mods preinstalled and default config for elytra trims
1. Install complementary
2. load shader

**Comment by kikugie** [comment]
I can't reproduce it with neither of the Complementary shaders, so it seems like a compatibility issue. Please find the minimal set of mods that cause this issue.
