### ISSUE TITLE
[Bug]: 3d skin layers in first person when using first person model mod

### ISSUE THREAD

**Issue by Th3Panda** [Kikugie/elytra-trims#77]
### Mod loader

Fabric

### Minecraft version

1.20.1

### Mod version

3.4.3

### Affected mods

- [X] Elytra Trims
- [ ] Extensions

### Bug description

When holding the elytra in your hand with both 3d skin layers and the first person model mod, you see the 3d skin layer when looking down.

![2024-07-21_06 34 43](https://github.com/user-attachments/assets/42852626-2af9-47aa-ac5c-066494f7283c)

**Comment by kikugie** [comment]
Resolved in 3.5.0
