### ISSUE TITLE
cant plave elytra into smithing table

### ISSUE THREAD

**Issue by redirecteddd** [Kikugie/elytra-trims#78]
### Mod loader

Fabric

### Minecraft version

1.21

### Mod version

3.4.3

### Affected mods

- [X] Elytra Trims
- [ ] Extensions

### Bug description

I cant place elytra into equipment slot

**Comment by kikugie** [comment]
Provide relevant information, such as the game log and detailed steps before submitting a report. Read the FAQ section on the mod page too.
