### ISSUE TITLE
Support for glowing armor

### ISSUE THREAD

**Issue by filips123** [Kikugie/elytra-trims#8]
## Motivation

This mod adds support for glowing elytra. However, this does not apply to armor, which could make trims look a bit inconstant if only elytra is glowing.

## Description

There should be support to apply glow ink sac to armor, in the same way as for elytra.

**Comment by kikugie** [comment]
This mod focuses on elytra, so armor features won't be added.

**Comment by filips123** [comment]
Well, it would be nice for more consistent looking trims, but sure... Also, would you accept PR that adds this feature or should it be done as a separate mod?

**Comment by kikugie** [comment]
Better as a separate mod, and I've seen some work in progress in the Fabric discord. Adding them isn't difficult, but it contradicts the design of this mod.
