### ISSUE TITLE
[Bug]: Crash on render with elytra in Elytra Slot added curio slot

### ISSUE THREAD

**Issue by team1257Simon** [Kikugie/elytra-trims#80]
### Mod loader

Fabric

### Minecraft version

1.21

### Mod version

3.4.4

### Affected mods

- [X] Elytra Trims
- [ ] Extensions

### Bug description

As soon as I equip an elytra in the back slot with this mod installed (trimmed or not), the game immediately crashes. The error is a NullPointerException (oof) that appears to refer to the item stack object being passed to the render method. Crash log is attached. The call stack shows a mixin related to that mod that appears to be part of this one.
The crash does not occur if the back slot is set to hidden (i.e. not rendering) before equipping, but if the render is then later turned on, the game immediately crashes. 
If loading the game with the elytra equipped, the crash occurs only when opening the inventory or otherwise doing something that renders the player's model.
[crash-2024-08-25_13.55.59-client.txt](https://github.com/user-attachments/files/16741432/crash-2024-08-25_13.55.59-client.txt)

### Steps to reproduce

1. Play the game with Elytra Trims and Elytra slot
2. Equip an elytra in the Back curio slot
The game freezes for a moment and then crashes. It does not matter if the elytra is trimmed, and the crash happens with both normal elytra and modded ones (such as Mekanism's HDPE elytra).

**Comment by kikugie** [comment]
Resolved in 3.5.0
