### ISSUE TITLE
[1.20.1] Cannot load or create world with Elytra Trims + Upgrade Aquatic

### ISSUE THREAD

**Issue by Diamondback88** [Kikugie/elytra-trims#83]
### Mod loader

Forge

### Minecraft version

1.20.1

### Mod version

3.5.2

### Affected mods

- [X] Elytra Trims
- [ ] Extensions

### Bug description

When attempting to load a world with Blueprint, Elytra Trims, Kotlin for Forge, and Upgrade Aquatic on recommended Forge version 47.1.3, the world will refuse to launch and only offer a "safe mode" option to launch the world. If you attempt to create a new world, the game will crash.

It's worth noting that this also happens on the latest NeoForge version for 1.20.1 (47.1.106); this is likely because this NeoForge version has parity with Forge version 47.1.3.

### Steps to reproduce

1. Install Blueprint, Elytra Trims, Kotlin for Forge, and Upgrade Aquatic.
2. Load an existing world.
3. Receive the error.

OR:
1. Install Blueprint, Elytra Trims, Kotlin for Forge, and Upgrade Aquatic.
2. Attempt to create a new world.
3. The game will crash.

### Relevant logs

https://mclo.gs/XHW4wIF

**Comment by SageofTurtles** [comment]
I'm encountering this issue as well, same mod version and environment.  I don't have Blueprint or Update Aquatic installed, but every time I try to create a world the game immediately crashes.  Crash log below for reference (sorry, I wasn't able to isolate which other mod(s) it's conflicting with, so it's a long list):  
[crash-2024-09-16_22.54.33-client.txt](https://github.com/user-attachments/files/17022676/crash-2024-09-16_22.54.33-client.txt)

**Comment by kikugie** [comment]
Has been fixed in 3.5.3 (a while ago)
