### ISSUE TITLE
[Bug]: Error prevents worlds from loading.

### ISSUE THREAD

**Issue by saoirse-source** [Kikugie/elytra-trims#84]
### Mod loader

Forge

### Minecraft version

1.20.1

### Mod version

3.5.2

### Affected mods

- [X] Elytra Trims
- [ ] Extensions

### Bug description

Elytratrims prevents loading of new and existing worlds in my modpack, worked fine on 3.5.0.
![image](https://github.com/user-attachments/assets/eef02b09-20d6-40e4-80ba-8d9d28e92ab5)

Discovered initially when attempting to boot my server and it errors out.
I've tested in a clean Forge 1.20.1 installation, with only Kotlin and ElytraTrims installed, and that functioned fine when I created a world.

Creating a new world immediately crashes, with it citing ModernFix as an additional potential cause - However I added this to my test installation with just ElytraTrims and didn't experience the same issues.
![image](https://github.com/user-attachments/assets/98cadd98-4ca1-434c-b809-359e85efd24a)

### Relevant logs

Server Erroring - https://mclo.gs/mNKgkVW
World Creation - https://mclo.gs/w9qh2yK

**Comment by kikugie** [comment]
Same as #83, will be fixed along with it
