### ISSUE TITLE
[Bug]: mixins squared issue

### ISSUE THREAD

**Issue by VaporeonScripts** [Kikugie/elytra-trims#88]
### Mod loader

NeoForge

### Minecraft version

1.21.1

### Mod version

Latest

### Affected mods

- [X] Elytra Trims
- [ ] Extensions

### Bug description

Crash when adding more culling,the issue seems to be caused by ur mod

### Steps to reproduce

Install this mod along more culling

### Relevant logs

https://mclo.gs/Fo1mAqx

**Comment by kikugie** [comment]
"additionallanterns" seems to cause the issue in question. Otherwise please report it on the mixinextras repo

**Comment by VaporeonScripts** [comment]
yeah,they said its not caused by them, but one of the errors comes from there, where do i find mixinextras repo?

**Comment by kikugie** [comment]
Sorry, mistaken mixinextras for mixinsquared: https://github.com/Bawnorton/MixinSquared

**Comment by VaporeonScripts** [comment]
https://github.com/Bawnorton/MixinSquared/issues/14#issuecomment-2383683721
ig they will handle it
