### ISSUE TITLE
[Bug]: Pattern and glow recipies are incorrectly displayed in EMI

### ISSUE THREAD

**Issue by Disketaa** [Kikugie/elytra-trims#89]
### Mod loader

Fabric

### Minecraft version

1.21.1

### Mod version

3.5.3

### Affected mods

- [X] Elytra Trims
- [X] Extensions

### Bug description

![image](https://github.com/user-attachments/assets/9fc3a056-d219-43fa-bf06-a6f90207ff5c)

Elytra dying and glowing were off via config, but recipes in EMI still appear

### Steps to reproduce

1. Install EMI
2. Disable elytra glowing & dying
3. Check for the elytra crafting recipe

**Comment by kikugie** [comment]
This is intentional to make the mod work server-side

**Comment by Disketaa** [comment]
Good point. I'll just hide the recipes by myself 👍

**Comment by Disketaa** [comment]
But how can I disable Elytra Dying?

**Comment by kikugie** [comment]
Neither of the features can be disabled
