### ISSUE TITLE
 elytratrims is incompatible with AllTheTrim and causes crashes

### ISSUE THREAD

**Issue by Cindystick** [Kikugie/elytra-trims#91]
Although BetterTrims is compatible with elytratrims and is also compatible with AllTheTrims (BetterTrims also creates effects for various special materials such as echo fragments, coal, slime balls and even progress interfaces),
However, elytratrims and AllTheTrim were incompatible, and the game crashed directly. After logging in again, all the original forging templates and elywings disappeared

**Comment by Bawnorton** [comment]
Lemme just link the other duplicate issues so we're not chasing this across multiple repos. Also logs please

https://github.com/Bawnorton/BetterTrims/issues/79
https://github.com/Bawnorton/AllTheTrims/issues/46

**Comment by Bawnorton** [comment]
Resolved in https://github.com/Bawnorton/BetterTrims/issues/79, needs to update ET to 3.5.4
