### ISSUE TITLE
Could you delete unnecessary console log please: BCLIB Consol log

### ISSUE THREAD

**Issue by suerion** [Kikugie/elytra-trims#92]
### Description

Could you disable please your unnecessary console log please, it is only for you necessary, but not for other player, i know the devs are not that easy, but theyr mod is also not that bad.. 

thanks

[        print("betterend") { "IHATEBCLIB ".repeat(Random().nextInt(20, 100)) }](https://github.com/kikugie/elytra-trims/blob/05093a166d022b5374bf31493a87f4b1fdd01686/src/main/kotlin/dev/kikugie/elytratrims/common/ETCommentary.kt#L8)

**Comment by kikugie** [comment]
No
