### ISSUE TITLE
[Request]: add support for "Functional Armor Trim"

### ISSUE THREAD

**Issue by vinnyg0621** [Kikugie/elytra-trims#94]
### Mod loader

Forge

### Minecraft version

1.20.1

### Mod version

3.5.4

### Affected mods

- [X] Elytra Trims
- [X] Extensions

### Bug description

support for functional armor trim mod:
[here](https://www.curseforge.com/minecraft/mc-mods/functional-armor-trim)

**Comment by kikugie** [comment]
Elytra Trims stores trims in the standard tag, so it should be able to do it by itself. For example https://www.curseforge.com/minecraft/mc-mods/better-trims does it without compatibility measures.
