### ISSUE TITLE
[Bug]: Banner patterns do not render with Vanilla Tweaks' (HD Shield Banner Patterns)

### ISSUE THREAD

**Issue by Xratedjunior** [Kikugie/elytra-trims#95]
### Mod loader

Fabric

### Minecraft version

1.20.1

### Mod version

3.5.4

### Affected mods

- [X] Elytra Trims
- [ ] Extensions

### Bug description

Creating an elytra does not show the banner pattern when Vanilla Tweaks' (HD Shield Banner Patterns) is also active.

### Steps to reproduce

1. Install Elytra Trims & Vanilla Tweaks (HD Shield Banner Patterns)
2. Elytra just shows as dyed, but the pattern is invisible.

**Comment by kikugie** [comment]
Open the Elytra Trims config from Mod Menu and enable "Use Banner Textures" setting

**Comment by Xratedjunior** [comment]
I tried, for me it doesn't change anything
