### ISSUE TITLE
[Bug]: Incompatibility with Vanilla Tweaks

### ISSUE THREAD

**Issue by QwertRvg** [Kikugie/elytra-trims#98]
### Mod loader

Fabric

### Minecraft version

1.20.1

### Mod version

3.5.4

### Affected mods

- [X] Elytra Trims
- [ ] Extensions

### Bug description

If VanillaTweaks is being used, with it's HD Banner Shields option enabled, banner patterns do not show up on the elytra.
Even if the config option to use the banner texture instead of the shield one is enabled.

Looks like this: (an Ominous banner was used here)
![image](https://github.com/user-attachments/assets/70c15d1d-4f25-41b3-80a3-c18fef522dc8)

If this can't be fixed, it'd be nice if it was listed as a conflict on the mod description page.

### Steps to reproduce

1. create a VanillaTweaks resource pack with the HD Banner Shield option enabled (https://vanillatweaks.net/picker/resource-packs/)
2. install Elytra Trims
3. Launch the Game and a World
4. Add the Resource Pack
5. Combine an Elytra with a Banner that includes a Banner Pattern
6. Wear the Elytra

**Comment by kikugie** [comment]
Open Elytra Trims config and enable banner textures there.

**Comment by QwertRvg** [comment]
as mentioned, this does not solve the issue
at least not for me

**Comment by kikugie** [comment]
Hm there indeed seems to be a bug with rescaling the texture
