### ISSUE TITLE
[Bug]: Compatability with Tinkers' Construct (Hephaestus)

### ISSUE THREAD

**Issue by westbot657** [Kikugie/elytra-trims#99]
### Mod loader

Fabric

### Minecraft version

1.20.1

### Mod version

3.5.4

### Affected mods

- [ ] Elytra Trims
- [ ] Extensions

### Bug description

Tinkers' Construct armor sets renders incorrectly as a 3D model when the setting for rendering the 3D elytra model in the inventory is on.

### Steps to reproduce

have tinkers' (called Hephaestus) and this mod
have 3D models on.
tinkers' slimeskulls, traveler armor, and plate armor sets renders as 3D chest piece models instead of their default item textures

**Comment by kikugie** [comment]
Hephaestus identifies all those items as elytras, so naturally they get the 3D model.
